spring:
  application:
    name: eureka

server:
  port: 8999
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8999/eureka
      